import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Desktop1(),
        ]),
      ),
    );
  }
}

class Desktop1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1440,
          height: 1518,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1440,
                  height: 56,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 147,
                top: 16,
                child: Text(
                  'Franchise Opportunities',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 232,
                top: 107,
                child: Text(
                  'CARTRIDE KINGS',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 66,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 147,
                top: 121,
                child: Container(
                  width: 70,
                  height: 71,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/70x71"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 396,
                top: 16,
                child: Text(
                  'Help',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 490,
                top: 16,
                child: Text(
                  'Feedback',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 968,
                top: 16,
                child: Text(
                  'hello@email.com',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 1172,
                top: 16,
                child: Text(
                  '0800 022 2 022',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 1110,
                top: 130,
                child: Container(
                  width: 183,
                  height: 53,
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.09, -1.00),
                      end: Alignment(-0.09, 1),
                      colors: [Color(0xFFFF9315), Color(0xFFE57D02)],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1169,
                top: 145,
                child: Text(
                  'CART (1)',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 859,
                top: 130,
                child: Container(
                  width: 233,
                  height: 53,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 19,
                        top: 15,
                        child: Text(
                          'SEARCH',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 16,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 233,
                          height: 53,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(side: BorderSide(width: 1)),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 188,
                        top: 14,
                        child: Container(
                          width: 25,
                          height: 25,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/25x25"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 147,
                top: 257,
                child: Container(
                  width: 1146,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 907,
                        top: 0,
                        child: Container(
                          width: 239,
                          height: 60,
                          decoration: BoxDecoration(color: Color(0xFF30A8FF)),
                        ),
                      ),
                      Positioned(
                        left: 941,
                        top: 17.84,
                        child: SizedBox(
                          width: 172,
                          height: 24.32,
                          child: Text(
                            'LOGIN / REGISTER',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 20,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 668,
                        top: 0,
                        child: Container(
                          width: 239,
                          height: 60,
                          decoration: BoxDecoration(color: Color(0xFF30A8FF)),
                        ),
                      ),
                      Positioned(
                        left: 723,
                        top: 17.84,
                        child: SizedBox(
                          width: 130,
                          height: 24.32,
                          child: Text(
                            'CONTACT US',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 20,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 429,
                        top: 0,
                        child: Container(
                          width: 239,
                          height: 60,
                          decoration: BoxDecoration(color: Color(0xFF30A8FF)),
                        ),
                      ),
                      Positioned(
                        left: 451,
                        top: 17.84,
                        child: SizedBox(
                          width: 196,
                          height: 24.32,
                          child: Text(
                            'TONER CARTRIDGES',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 20,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 190,
                        top: 0,
                        child: Container(
                          width: 239,
                          height: 60,
                          decoration: BoxDecoration(color: Color(0xFF30A8FF)),
                        ),
                      ),
                      Positioned(
                        left: 228,
                        top: 17.84,
                        child: SizedBox(
                          width: 164,
                          height: 24.32,
                          child: Text(
                            'INK CARTRIDGES',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 20,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 190,
                          height: 60,
                          decoration: BoxDecoration(color: Color(0xFF1C99F3)),
                        ),
                      ),
                      Positioned(
                        left: 65,
                        top: 17.84,
                        child: SizedBox(
                          width: 59,
                          height: 24.32,
                          child: Text(
                            'HOME',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 20,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 368,
                child: Container(
                  width: 1440,
                  height: 454,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 1440,
                          height: 454,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/1440x454"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: -2,
                        top: -215.21,
                        child: Container(
                          width: 1456,
                          height: 884.42,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/1456x884"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 239,
                top: 518,
                child: Container(
                  width: 963,
                  height: 176,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 961,
                top: 625,
                child: Container(
                  width: 195,
                  height: 49,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 195,
                          height: 49,
                          decoration: ShapeDecoration(
                            color: Color(0xFFFB9012),
                            shape: RoundedRectangleBorder(side: BorderSide(width: 0.30)),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 12,
                        top: 12.47,
                        child: SizedBox(
                          width: 175,
                          height: 26.73,
                          child: Text(
                            'FIND CARTRIDGES',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 20,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 286,
                top: 624,
                child: Container(
                  width: 195,
                  height: 46.84,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 195,
                          height: 46.84,
                          decoration: ShapeDecoration(
                            gradient: LinearGradient(
                              begin: Alignment(0.04, -1.00),
                              end: Alignment(-0.04, 1),
                              colors: [Colors.white, Color(0xBA828282)],
                            ),
                            shape: RoundedRectangleBorder(side: BorderSide(width: 0.30)),
                            shadows: [
                              BoxShadow(
                                color: Color(0x54000000),
                                blurRadius: 4,
                                offset: Offset(0, 3),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 8,
                        top: 13.63,
                        child: SizedBox(
                          width: 128,
                          height: 20.44,
                          child: Text(
                            'Printer Brand',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 174,
                        top: 28.10,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-3.14),
                          child: Container(
                            width: 11,
                            height: 9.37,
                            decoration: ShapeDecoration(
                              color: Colors.black,
                              shape: StarBorder.polygon(sides: 3),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 511,
                top: 624,
                child: Container(
                  width: 195,
                  height: 46.84,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 195,
                          height: 46.84,
                          decoration: ShapeDecoration(
                            gradient: LinearGradient(
                              begin: Alignment(0.04, -1.00),
                              end: Alignment(-0.04, 1),
                              colors: [Colors.white, Color(0xBA828282)],
                            ),
                            shape: RoundedRectangleBorder(side: BorderSide(width: 0.30)),
                            shadows: [
                              BoxShadow(
                                color: Color(0x54000000),
                                blurRadius: 4,
                                offset: Offset(0, 3),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 8,
                        top: 13.63,
                        child: SizedBox(
                          width: 128,
                          height: 20.44,
                          child: Text(
                            'Printer Series',
                            style: TextStyle(
                              color: Colors.black.withOpacity(0.5),
                              fontSize: 16,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 174,
                        top: 28.10,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-3.14),
                          child: Container(
                            width: 11,
                            height: 9.37,
                            decoration: ShapeDecoration(
                              color: Colors.black.withOpacity(0.5),
                              shape: StarBorder.polygon(sides: 3),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 736,
                top: 625,
                child: Container(
                  width: 195,
                  height: 46.84,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 195,
                          height: 46.84,
                          decoration: ShapeDecoration(
                            gradient: LinearGradient(
                              begin: Alignment(0.04, -1.00),
                              end: Alignment(-0.04, 1),
                              colors: [Colors.white, Color(0xBA828282)],
                            ),
                            shape: RoundedRectangleBorder(side: BorderSide(width: 0.30)),
                            shadows: [
                              BoxShadow(
                                color: Color(0x54000000),
                                blurRadius: 4,
                                offset: Offset(0, 3),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 8,
                        top: 14,
                        child: SizedBox(
                          width: 135,
                          height: 20,
                          child: Text(
                            'Printer Model',
                            style: TextStyle(
                              color: Colors.black.withOpacity(0.5),
                              fontSize: 16,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 174,
                        top: 28.10,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-3.14),
                          child: Container(
                            width: 11,
                            height: 9.37,
                            decoration: ShapeDecoration(
                              color: Colors.black.withOpacity(0.5),
                              shape: StarBorder.polygon(sides: 3),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 239,
                top: 512,
                child: Container(
                  width: 481,
                  height: 74.76,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/481x75"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 377,
                top: 529,
                child: Text(
                  '3-Step Easy Search®',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 720,
                top: 518,
                child: Container(
                  width: 482,
                  height: 51,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 870,
                top: 529,
                child: Text(
                  'Search by Serial Number',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 20,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 555,
                top: 912,
                child: Text(
                  'FEATURED PRODUCTS',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 30,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 216,
                top: 1013,
                child: Container(
                  width: 312,
                  height: 407,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 312,
                          height: 407,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(side: BorderSide(width: 0.30)),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 26.20,
                                offset: Offset(4, 6),
                                spreadRadius: 2,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 17,
                        top: 20,
                        child: Container(
                          width: 278,
                          height: 236,
                          decoration: BoxDecoration(color: Color(0xFFD6D7E4)),
                        ),
                      ),
                      Positioned(
                        left: 166,
                        top: 350,
                        child: Container(
                          width: 129,
                          height: 43,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 129,
                                  height: 43,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFFB9012),
                                    shape: RoundedRectangleBorder(side: BorderSide(width: 0.30)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 15,
                                top: 13,
                                child: SizedBox(
                                  width: 99.44,
                                  height: 23.89,
                                  child: Text(
                                    'ADD TO CART',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 14,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w600,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 42,
                        top: 41,
                        child: Container(
                          width: 228,
                          height: 215,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/228x215"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 28,
                        top: 283,
                        child: Text(
                          'HP 62 Black Ink Cartridge',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 18,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 28,
                        top: 357,
                        child: Text(
                          '\$9.49',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 24,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 28,
                        top: 310,
                        child: Text(
                          '(HPC2P04AE)',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 13,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w275,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 564,
                top: 1013,
                child: Container(
                  width: 312,
                  height: 407,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 312,
                          height: 407,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 312,
                                  height: 407,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(side: BorderSide(width: 0.30)),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x3F000000),
                                        blurRadius: 26.20,
                                        offset: Offset(4, 6),
                                        spreadRadius: 2,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 17,
                                top: 20,
                                child: Container(
                                  width: 278,
                                  height: 236,
                                  decoration: BoxDecoration(color: Color(0xFFD6D7E4)),
                                ),
                              ),
                              Positioned(
                                left: 166,
                                top: 350,
                                child: Container(
                                  width: 129,
                                  height: 43,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 129,
                                          height: 43,
                                          decoration: ShapeDecoration(
                                            color: Color(0xFFFB9012),
                                            shape: RoundedRectangleBorder(side: BorderSide(width: 0.30)),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 15,
                                        top: 13,
                                        child: SizedBox(
                                          width: 99.44,
                                          height: 23.89,
                                          child: Text(
                                            'ADD TO CART',
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontSize: 14,
                                              fontFamily: 'Poppins',
                                              fontWeight: FontWeight.w600,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 28,
                                top: 283,
                                child: Text(
                                  'Canon MF-3110 Toner',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 18,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 28,
                                top: 357,
                                child: Text(
                                  '\$36.45',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 24,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 28,
                                top: 310,
                                child: Text(
                                  '(C2P04AE)',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 13,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w275,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 17,
                        top: 20,
                        child: Container(
                          width: 284,
                          height: 239,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/284x239"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 912,
                top: 1013,
                child: Container(
                  width: 312,
                  height: 407,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 312,
                          height: 407,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 312,
                                  height: 407,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(side: BorderSide(width: 0.30)),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x3F000000),
                                        blurRadius: 26.20,
                                        offset: Offset(4, 6),
                                        spreadRadius: 2,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 17,
                                top: 20,
                                child: Container(
                                  width: 278,
                                  height: 236,
                                  decoration: BoxDecoration(color: Color(0xFFD6D7E4)),
                                ),
                              ),
                              Positioned(
                                left: 42,
                                top: 41,
                                child: Container(
                                  width: 228,
                                  height: 215,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/228x215"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 28,
                                top: 283,
                                child: Text(
                                  'HP 62 Black Ink Cartridge',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 18,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 28,
                                top: 357,
                                child: Text(
                                  '\$5.99',
                                  style: TextStyle(
                                    color: Color(0xFFFF0000),
                                    fontSize: 24,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 28,
                                top: 346,
                                child: Text(
                                  '\$9.49',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 12,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 28,
                                top: 310,
                                child: Text(
                                  '(HPC2P04AE)',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 13,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w275,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 166,
                        top: 350,
                        child: Container(
                          width: 129,
                          height: 43,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 129,
                                  height: 43,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFFB9012),
                                    shape: RoundedRectangleBorder(side: BorderSide(width: 0.30)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 15,
                                top: 13,
                                child: SizedBox(
                                  width: 99.44,
                                  height: 23.89,
                                  child: Text(
                                    'ADD TO CART',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 14,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w600,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 1260,
                top: 1158,
                child: Container(
                  width: 98,
                  height: 98,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/98x98"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 180,
                top: 1158,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                  child: Container(
                    width: 98,
                    height: 98,
                    decoration: BoxDecoration(
                      image: DecorationImage(
                        image: NetworkImage("https://via.placeholder.com/98x98"),
                        fit: BoxFit.fill,
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
